# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 02:11
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=sorl.thumbnail.fields.ImageField(upload_to='static/images'),
        ),
    ]
